### PR TITLE
Support keyword args and yields sections

### LINKED ISSUE #324: Support "Yields" in docstrings
**Is your feature request related to a problem? Please describe.**
Per the [Google styleguide](https://google.github.io/styleguide/pyguide.html#doc-function-returns), the keyword `Yields` is used for generators. However, when using `Yields` in a docstring, it is not parsed by `mkdocstrings`:

image

**Describe the solution you'd like**
I'd like `Yields` to be parsed in the same manner that `Returns` is. :)

### PR DESCRIPTION
**Pull request by pawamoy**
Closes #324 and #205

### CODE REVIEW

**Comment by pawamoy** [comment]
CI needs #330 to pass.

**Comment by oprypin** [comment]
Actually... I don't understand the purpose behind a "keyword args" section. The descriptions of all parameters can be within one section, why should they be separated?
The actual viability of passing arguments should be visible from the function's signature.

**Comment by pawamoy** [comment]
The purpose of the Keyword Argument section is to be able to document arguments that can be passed through `**kwargs`, and to enjoy the same formatting as for regular Arguments sections.

Consider this:

```python
def function(a, b, **kwargs):
    c = kwargs.pop("c")
    d = kwargs.pop("d")
    # use a, b, c, d
```

You can document `a`, `b`, and `**kwargs` in the Arguments section, but not `c` and `d` directly, as they are not part of the signature (linters not happy). You could document them in the `**kwargs` description, but you'd have to use plain Markdown formatting for anything a bit elaborate. Instead, with a Keyword Arguments section, you can document `c` and `d` just like any other argument:

```
Keyword Arguments:
    c (int): Description.
    d (list[str] | None): Description
```

**Comment by oprypin** [comment]
Wait, I thought that Python has eliminated all cases where you'd have to rely on `**kwargs` to serve particularly-named keyword-only arguments. Wouldn't it be good to just hope that the last usages of this will die out soon and encourage writing the arguments directly?
```python
def function(a, b, *, c, d):
```

**Comment by pawamoy** [comment]
You have good arguments as always @oprypin :slightly_smiling_face: 
I don't know if it's reasonable to expect that this use of `**kwargs` will disappear (its only use apart from swallowing unwanted arguments?). Support for this was explicitly requested by users :confused:

**Comment by oprypin** [comment]
Well, if supporting this never pops up in any way except when people write `Keyword arguments:`, that's fine. (I was afraid that this would *automatically* create such sections where it didn't before). But I wouldn't change correct wording to wrong just to match this rare use case.

BTW they could instead describe `kwargs` as its own item within `Args`, with normal Markdown sub-lists in it

**Comment by pawamoy** [comment]
> BTW they could instead describe kwargs as its own item within Args, with normal Markdown sub-lists in it

Yes that's what I initially replied in the original issue, #205.

> I was afraid that this would automatically create such sections where it didn't before

Oh no, it's only rendered when a "Keyword arguments" section is found indeed.

> But I wouldn't change correct wording to wrong just to match this rare use case.

Agreed. Then I'll totally revise what I said earlier, and change the section title to "Keyword parameters". Maybe "Other parameters", from Numpydoc, would be even more appropriate.

**Comment by oprypin** [comment]
OK! Now no issue from my side.
I will *not* do a super careful review of all the content, so that's all.
Thanks

**Comment by pawamoy** [comment]
Failures came from a precedent version of PDM which fixed the KeyError issue.

**Pull request merged**
