### PR TITLE
docs: Use literate nav to generate reference sidebar

### PR DESCRIPTION
**Pull request by pawamoy**
Related to #179 and #268.

### CODE REVIEW

**Comment by oprypin** [comment]
I tried a lot of approaches, anything that would significantly simplify this. But couldn't come up with anything good.

So I can only offer a slight improvement of the code that you have here: https://github.com/mkdocstrings/mkdocstrings/commit/54b12e954baa217b29a45340c06325a37188918b

**Comment by pawamoy** [comment]
Clever improvements, thanks! Any reason why you set it back to SUMMARY.md?

**Comment by oprypin** [comment]
I use the name SUMMARY.md in every project. And it is a really special file so it shouldn't have a normal name.

The name originated from GitBook which uses this file name to specify the nav in the same way.

**Comment by oprypin** [comment]
There's also the option of upstreaming this code.

See
https://github.com/oprypin/mkdocs-gen-files/commit/literate-nav
https://github.com/oprypin/mkdocstrings/commit/literate-nav-3

**Comment by oprypin** [comment]
Based on previous mentions in chat, I figured I'd push my changes *to* this pull request. I also released the code in mkdocs-gen-files. Check it out.

**Comment by pawamoy** [comment]
This is greaaaaaaaaaaaaat :smile: 
We should definitely document this in mkdocstrings docs now :stuck_out_tongue: 
But this can be done in another PR.
(I can't approve my own PR so if you want to improve, otherwise I'll force merge)

**Review by oprypin — APPROVED** [review]

**Comment by lucmos** [comment]
@pawamoy Thanks for this PR! 
Do you have an example of how to use this feature?

It seems some files touched by this PR do not exist anymore on master

**Comment by oprypin** [comment]
The relevant documentation is
https://oprypin.github.io/mkdocs-literate-nav/#programmatic-control-over-the-nav
\- and the docs are unfortunately kind of a circular reference back to this code, but oh well...

**Comment by lucmos** [comment]
Thanks for the fast reply @oprypin 

It is working.
Unfortunately getting the expected result is quite hard. E.g. private modules or pages that would end up being empty must be excluded, namespaces (folders without `__init__.py`) must be taken into account, as the public API from `__all__`. I am not sure it is possible to avoid the generation of empty pages in the scope of the script...

I feel like to get it right much of the code that handles the default docs generation should be duplicated. It would be enough to somehow change the header levels in the single-page into multiple files :thinking:

**Comment by pawamoy** [comment]
Hi @lucmos, thanks a lot for sharing this.

Indeed, this example works fine for simple page generation. For more complex selection/rendering options, the script can become very complex. In that case maybe the best option is to actually write the markdown pages as it allows much more granular configuration. Of course some features could be added, like respecting `__all__` :slightly_smiling_face:

**Pull request merged**
