### PR TITLE
feat: Add `show_signature` rendering option

### LINKED ISSUE #341: `show_signature` rendering option
**Is your feature request related to a problem? Please describe.**
Functions that have docstrings with documented parameters result in redundant documentation of the parameters. First you've got the function name with the signature showing its parameters, and then below that you've got a parameter table with columns `Name`, `Type`, `Description`, `Default`.

**Describe the solution you'd like**
I would like the addition of a `show_signature` rendering option. It would default to true (if for no other reason than backwards compatibility). When it is true, mkdocstrings would work as it does now. When it is false, the docs would render the function name (and potentially the root path), but not the signature (i.e. everything between the parentheses). This new rendering option would override `show_signature_annotations`, as it doesn't make sense to show signature annotations when the entire signature is not being shown.

### PR DESCRIPTION
**Pull request by WillDaSilva**
Closes #341

### CODE REVIEW

**Comment by WillDaSilva** [comment]
@pawamoy looks like the CI is failing to install the project dependencies. Doesn't appear to be related to my changes.

**Comment by pawamoy** [comment]
Hey @WillDaSilva, thanks for the PR! No indeed it's not related to your changes. I tried locking the deps locally, and it works, so I'm not sure what's wrong in CI. Will investigate later :slightly_smiling_face:

**Comment by pawamoy** [comment]
Sorry, misclicked.

**Comment by pawamoy** [comment]
Hey @WillDaSilva, can you rebase on master? That should fix CI.

**Comment by pawamoy** [comment]
Alright, good to go, thanks!
Just so you know: I've started to extract the Python handler into its own repository: https://github.com/mkdocstrings/python-legacy.
With your permission, I'll just reapply your modifications and set you as co-author (unless you want to send a PR).
I'll also reapply your modifications in the *new* Python handler: https://github.com/mkdocstrings/python :joy: (unless again you want to send a PR).

That transition period will be hard to maintain :sweat_smile:

**Review by pawamoy — APPROVED** [review]

**Comment by WillDaSilva** [comment]
Please do whatever is easiest for you.

I suppose I should make any future contributions against the new Python handler, and simply accept that it won't be available until it is released.

If that ever becomes an issue I'll temporarily host a fork of the relevant package on my company's internal PyPI server, so there's no additional pressure to release quickly.

**Comment by pawamoy** [comment]
I'm giving my all to make this as quick and smooth as possible, so I hope it won't become an issue!

**Pull request merged**
