### PR TITLE
fix: `custom_templates` config was dropped in previous commit

### PR DESCRIPTION
**Pull request by oprypin**

### CODE REVIEW

**Review by pawamoy — APPROVED** [review]
Damn implicit tuples!

**Comment by oprypin** [comment]
Need to switch to `ruff format` ASAP :joy: 
it would've formatted as

```diff
-    custom_templates = opt.Optional(opt.Dir(exists=True)),
+    custom_templates = (opt.Optional(opt.Dir(exists=True)),)
```

https://docs.astral.sh/ruff/formatter/black/#single-element-tuples-are-always-parenthesized

**Comment by pawamoy** [comment]
Yeah it has some valuable formatting improvements over Black, I'm OK with using it :slightly_smiling_face:

**Comment by oprypin** [comment]
No objections for your projects :)

For myself, I'm just wary about the rollout of the "preview style" of Black which will be something that affects both Black and Ruff as it follows it. And maybe I'll use that opportunity to switch.

**Pull request merged**
