### PR TITLE
refactor: Report inventory loading errors

### LINKED ISSUE #157: Include only specific inherited members
**Is your feature request related to a problem? Please describe.**
My class `A` that I want to document is inheriting functions from a base class `Base`. However, for class `A` I only want to add a subset of the functions of `Base` to the docs. I can use `inherited_members: true` and then filter out the functions I don't want to use. But when doing this for multiple modules it becomes a bit messy and means I always have to check when adding new functionality in the code.

**Describe the solution you'd like**
I'd like `inherited_members` to work exactly like `members`. Instead of just `bool`, it can be `bool, or list of str`. This way I could define the specific inherited functions I want to include. The default could still be `False`.

```
::: classA
    selection:
      inherited_members:
        - inherited_method_a
        - inherited_method_b
```

### PR DESCRIPTION
**Pull request by pawamoy**
Closes #157

### CODE REVIEW

**Comment by oprypin** [comment]
I'll have a few style suggestions, hold up

**Comment by oprypin** [comment]
https://github.com/oprypin/mkdocstrings/commit/e3ccb943b83a2d0c703a954eeeef3f28f6af2c16  is my style suggestions.

In fact at this point I took out `ChainMap`, it's just a hinderance and [doesn't do anything smart whatsoever](https://github.com/python/cpython/blob/705508850026dd13121b469290e27c29bd8ef20c/Lib/collections/__init__.py#L1012-L1016).

**The edited code is untested.**

**Comment by oprypin** [comment]
Ah yes the edited code doesn't work :D

**Comment by oprypin** [comment]
Impressive that there is test coverage for this 😊
https://github.com/mkdocstrings/mkdocstrings/blob/e5522af09d9a4b88cec9e3215b9db66865339d2f/tests/test_inventory.py#L38

**Comment by pawamoy** [comment]
Thanks, great suggestions!

> Impressive that there is test coverage for this blush

Haha yeah :sweat_smile:? Is this how you found out your edited code didn't work?

**Comment by pawamoy** [comment]
Suggestions applied :slightly_smiling_face:

**Comment by oprypin** [comment]
Yes :)
Nice

**Comment by pawamoy** [comment]
Anything else? Care to approve :slightly_smiling_face: ?

**Review by oprypin — APPROVED** [review]

**Pull request merged**
