### PR TITLE
Compatibility with MkDocs 1.2: livereload isn't guaranteed now

### LINKED ISSUE #295: Incompatibility with mkdocs 1.2.
**Describe the bug**
The new released [mkdocs 1.2](https://pypi.org/project/mkdocs/1.2/) includes `livereload`, not as a dependency. Resulting in an import error:
```python
  File "/usr/local/lib/python3.9/site-packages/mkdocstrings/plugin.py", line 18, in <module>
    from livereload import Server
ModuleNotFoundError: No module named 'livereload'
```

**To Reproduce**
1. `pip install mkdocstrings`
2. `python -c 'import mkdocstrings.plugin'`

**Expected behavior**
No error.

**Information (please complete the following information):**
- `mkdocstrings` version: 0.15.1

### PR DESCRIPTION
**Pull request by oprypin**
MkDocs doesn't depend on 'livereload' library anymore, and neither should we, but we import it for the type annotation, which is now also wrong.

I also take this opportunity to drop compatibility with MkDocs 1.1.0 (without dropping 1.1.1)'

Fixes #295

### CODE REVIEW

**Comment by jmaupetit** [comment]
Thank you for this! :pray: Looking for these changes to be merged and released to upgrade to `mkdocs` 1.2.

**Comment by pawamoy** [comment]
Hey @oprypin, thanks a lot for the quick fix (and sorry for the slow reactivity, I've been quite busy these last three days). I'll merge this and try to release 0.15.2 as soon as possible as this issue can be quite annoying.

**Review by pawamoy — APPROVED** [review]

**Comment by pawamoy** [comment]
In fact I think we'll need to release 0.16 for this.

**Comment by oprypin** [comment]
@pawamoy Well whatever it will be, if you can't comfortably work on this release, please just grant me access to PyPI. Or let me know if I can help otherwise.

**Comment by pawamoy** [comment]
I'll grant you access to PyPI (reducing the bus factor yay) :slightly_smiling_face:
Feel free to push 0.15.2 with a usual changelog entry or a simplified one.
I'll prioritize (on my own end) updating docs for 0.16 during the next few days.

**Comment by jmaupetit** [comment]
Thank you both @oprypin & @pawamoy :heart:

**Pull request merged**
